cache:
    key: apt-cache
    paths:
        - apt-cache/

before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -qq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y -qq cmake libsdl2-dev libglew-dev libglm-dev libassimp-dev
    - cmake --version

build:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake ../
        - make
